# Generated by Django 6.0.2 on 2026-04-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.TextField(blank=True, help_text='Pool, Gym, Restaurant, Parking, etc.'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='state',
            field=models.CharField(blank=True, help_text='State/Province', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
