# Generated by Django 6.0.2 on 2026-04-06 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0002_hotel_amenities_hotel_image_hotel_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('paymaya', 'PayMaya'), ('grabpay', 'GrabPay'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal')], default='gcash', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='GCash/Reference Number', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotel',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Bank Account Name', max_length=200),
        ),
        migrations.AddField(
            model_name='hotel',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='business_permit',
            field=models.FileField(blank=True, help_text='Upload Business Permit', null=True, upload_to='business_permits/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='business_permit_number',
            field=models.CharField(blank=True, help_text='Business Permit Number', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='dti_registration',
            field=models.FileField(blank=True, help_text='DTI/SEC Registration', null=True, upload_to='dti_registrations/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='mayors_permit',
            field=models.FileField(blank=True, help_text="Mayor's Permit", null=True, upload_to='mayors_permits/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tin_number',
            field=models.CharField(blank=True, help_text='Tax Identification Number', max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes about verification'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_hotels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending_payment', 'Awaiting Payment'), ('payment_uploaded', 'Payment Uploaded - Pending Verification'), ('payment_verified', 'Payment Verified'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('verified', 'Payment Verified'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
